name = "ODEConvergenceTester"
uuid = "42a5c2e1-f365-4540-8ca5-3684de3ecd95"
authors = ["CliMA Contributors <clima-software@caltech.edu>"]
version = "0.2.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
SciMLBase = "1, 2"
julia = "1.4"
